ci: pull in latest changes

diff --git a/bin/release-legacy-chart b/bin/release-legacy-chart
--- a/bin/release-legacy-chart
+++ b/bin/release-legacy-chart
@@ -11,6 +11,8 @@ function usage() {
     echo "    -i <index.yaml>   The legacy index file (only valid i.c.w. -f)."
     echo "    -d <dir>          Release all .tgz files within the provided directory."
     echo "                      The index file defaults to <dir>/index.yaml."
+    echo "    -r                Skip creation of a GitHub release."
+    echo "    -u                Skip upload of GitHub release asset."
     echo ""
     echo "All provided files need to follow the format:"
     echo "  <chart-name>-<semantic-version>.tgz"
@@ -20,9 +22,13 @@ function usage() {
     exit 0
 }
 
+function fatal() {
+    error "${@}"
+    exit 1
+}
+
 function error() {
     echo "${1}" 1>&2
-    exit 1
 }
 
 function create_release() {
@@ -31,16 +37,16 @@ function create_release() {
     index="${2}"
 
     if [[ ! -f ${file} ]]; then
-        error "${file} is not a file"
+        fatal "${file} is not a file"
     fi
 
     if [[ ! -f ${index} ]]; then
-        error "${index} is not a file"
+        fatal "${index} is not a file"
     fi
 
     file_name=$(basename "${file}")
     if [[ ! "${file_name}" =~ ^([[:alpha:][:digit:]\.\_\-]+)-([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(-[[:alpha:][:digit:]\.\-]+)?)\.tgz$ ]]; then
-        error "${file_name} is not valid: use format <chart-name>-<semantic-version>.tgz"
+        fatal "${file_name} is not valid: use format <chart-name>-<semantic-version>.tgz"
     fi
 
     tag="${file_name%.*}"
@@ -49,38 +55,50 @@ function create_release() {
 
     mkdir -p "/tmp/github/${tag}"
 
-    command="curl -s -o \"/tmp/github/${tag}/release.json\" -w '%{http_code}' \
-        --request POST \
-        --header 'authorization: Bearer ${GITHUB_TOKEN}' \
-        --header 'content-type: application/json' \
-        --data '{\"tag_name\": \"${tag}\"}' \
-        https://api.github.com/repos/wielewout/helm-charts/releases"
-    http_code=$(eval "${command}")
-    if [ "${http_code}" != "201" ]; then
-        error "Release ${tag} failed with code '${http_code}'"
-    fi
-
-    echo "Created release ${tag}"
-
-    url=$(jq -r .upload_url "/tmp/github/${tag}/release.json" | cut -d '{' -f '1')
-    command="curl -s -o \"/tmp/github/${tag}/upload.json\" -w '%{http_code}' \
-        --request POST \
-        --header 'authorization: Bearer ${GITHUB_TOKEN}' \
-        --header 'Content-Type: application/octet-stream' \
-        --data-binary @\"${file}\" \
-        ${url}?name=${file_name}"
-    http_code=$(eval "${command}")
-    if [ "${http_code}" != "201" ]; then
-        error "Upload ${file_name} failed with code '${http_code}'"
-    fi
-
-    echo "Asset ${file_name} uploaded"
-
     yq ".entries.${chart}[] | select(.version == \"${version}\")" "${index}" > "/tmp/github/${tag}/index.yaml"
-    yq -i ".urls[0] = \"https://github.com/Wielewout/helm-charts/releases/download/${tag}/${file_name}\"" "/tmp/github/${tag}/index.yaml"
+    if [ ! -s "/tmp/github/${tag}/index.yaml" ]; then
+        fatal "${tag} is not present in the provided legacy index file"
+    fi
+
+    yq -i ".urls[0] = \"https://github.com/wielewout/helm-charts/releases/download/${tag}/${file_name}\"" "/tmp/github/${tag}/index.yaml"
     yq -i ".entries.${chart} += [load(\"/tmp/github/${tag}/index.yaml\")]" "${GIT_ROOT}/index.yaml"
 
     echo "Index file updated"
+
+    if [ "${release}" != true ] ; then
+        echo "Skipping creation of release ${tag}"
+    else
+        command="curl -s -o \"/tmp/github/${tag}/release.json\" -w '%{http_code}' \
+            --request POST \
+            --header 'authorization: Bearer ${GITHUB_TOKEN}' \
+            --header 'content-type: application/json' \
+            --data '{\"tag_name\": \"${tag}\", \"name\": \"${tag}\", \"body\": \"Legacy chart release\"}' \
+            https://api.github.com/repos/wielewout/helm-charts/releases"
+        http_code=$(eval "${command}")
+        if [ "${http_code}" != "201" ]; then
+            fatal "Release ${tag} failed with code '${http_code}'"
+        fi
+
+        echo "Created release ${tag}"
+    fi
+
+    if [ "${upload}" != true ] ; then
+        echo "Skipping upload of asset ${file_name}"
+    else
+        url=$(jq -r .upload_url "/tmp/github/${tag}/release.json" | cut -d '{' -f '1')
+        command="curl -s -o \"/tmp/github/${tag}/upload.json\" -w '%{http_code}' \
+            --request POST \
+            --header 'authorization: Bearer ${GITHUB_TOKEN}' \
+            --header 'Content-Type: application/octet-stream' \
+            --data-binary @\"${file}\" \
+            ${url}?name=${file_name}"
+        http_code=$(eval "${command}")
+        if [ "${http_code}" != "201" ]; then
+            fatal "Upload ${file_name} failed with code '${http_code}'"
+        fi
+
+        echo "Asset ${file_name} uploaded"
+    fi
 }
 
 function handle_file() {
@@ -102,7 +120,10 @@ file=""
 directory=""
 index=""
 
-while getopts ":hf:d:i:" opt; do
+release=true
+upload=true
+
+while getopts ":hf:d:i:ru" opt; do
     case ${opt} in
         h )
             usage
@@ -119,22 +140,28 @@ while getopts ":hf:d:i:" opt; do
                 index="${directory}/index.yaml"
             fi
         ;;
+        r )
+            release=false
+        ;;
+        u )
+            upload=false
+        ;;
         \? )
-            error "Invalid Option: -${OPTARG}"
+            fatal "Invalid Option: -${OPTARG}"
         ;;
         : )
-            error "Invalid option: ${OPTARG} requires an argument"
+            fatal "Invalid option: ${OPTARG} requires an argument"
         ;;
     esac
 done
 shift $((OPTIND -1))
 
 if [[ ! "$(yq --version)" =~ .*mikefarah/yq.* ]]; then
-    error "Make sure to install mikefarah/yq"
+    fatal "Make sure to install mikefarah/yq"
 fi
 
 if [[ "${index}" == "" ]]; then
-    error "No legacy index file is provided"
+    fatal "No legacy index file is provided"
 fi
 
 git checkout gh-pages > /dev/null
